{
 "title": "Debugtools",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests by route",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(debugtools_requests[1m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(debugtools_errors[1m]))"
    }
   ]
  },
  {
   "title": "Files uploaded",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(debugtools_files_uploaded)" }
   ]
  }
 ]
}